### ISSUE TITLE
Failed to start TIA application.

### ISSUE THREAD

**Issue by YasuKatsuno** [ibmjstart/bluemix-sample-tia-node#8]
Hello,

It was failed to start TIA Node.js application, although it had been success until last November.
It can be guessed that the version mismatch happens and package.json should be revised.
Which part should be updated?

package.json
------------------
{
  "name": "bluemix-sample-tia-node",
  "version": "0.1.0",
  "engines": {
    "node": "0.8.x"
  },
  "scripts": {
    "start": "node lib/cli.js"
  },
  "dependencies": {
    "async": "0.2.x",
    "express": "3.3.x",
    "nano": "~5.10.0"
  },
  "devDependencies": {
    "coffee-script": "1.6.x",
    "shelljs": "0.1.x",
    "supervisor": "0.5.x"
  }
}

Error message
-------------------
Preparing to start hci-ntia... OK                                                                                                                                        
-----> Downloaded app package (508K)                                                                                                                                       
-----> Node.js Buildpack Version: v1.12-20150130-1059                                                                                                                         
-----> Resolving node version by IBM
-----> Requested node range:  0.8.x
-----> Resolved node version: 0.8.28
-----> Downloading and installing node                                                                                                                                     
-----> Checking and configuring service extensions
-----> Installing dependencies                                                                                                                                                
       npm WARN package.json bluemix-sample-tia-node@0.1.0 No repository field.
       ......
       npm WARN package.json range-parser@0.0.4 No repository field.
       ......
       npm WARN package.json methods@0.0.1 No readme data.
       ......
       npm WARN package.json cookie-signature@1.0.1 No repository field.   
       ......
       npm ERR! Error: No compatible version found: request@'^2.44.0'
       npm ERR! Valid install targets:
       npm ERR! ["0.10.0","0.8.3","0.9.0","0.9.1","0.9.5","1.0.0","1.1.0","1.1.1","1.2.0","1.9.0","1.9.1","1.9.2","1.9.3","1.9.5","1.9.7","1.9.8","1.9.9","2.0.0","2.0.1","2.0.2","2.0.3","2.0.4","2.0.5","2.1.0","2.1.1","2.2.0","2.2.5","2.2.6","2.2.9","2.9.0","2.9.1","2.9.2","2.9.3","2.9.100","2.9.150","2.9.151","2.9.152","2.9.153","2.9.200","2.9.201","2.9.202","2.9.203","2.10.0","2.11.0","2.11.1","2.11.2","2.11.3","2.11.4","2.12.0","2.14.0","2.16.0","2.16.2","2.16.4","2.16.6","2.18.0","2.19.0","2.20.0","2.21.0","2.22.0","2.23.0","2.24.0","2.25.0","2.26.0","2.27.0","2.28.0","2.29.0","2.30.0","2.31.0","2.32.0","2.33.0","2.34.0","2.35.0","2.36.0","2.37.0","2.38.0","2.39.0","2.40.0","2.41.0","2.42.0","2.43.0","2.44.0","2.45.0","2.46.0","2.47.0","2.48.0","2.49.0","2.50.0","2.51.0","2.52.0","2.53.0"]
       npm ERR!     at installTargetsError (/tmp/staged/app/vendor/node/lib/node_modules/npm/lib/cache.js:719:10)
       npm ERR!     at /tmp/staged/app/vendor/node/lib/node_modules/npm/lib/cache.js:641:10
       npm ERR!     at RegClient.get_ (/tmp/staged/app/vendor/node/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:101:14)
       npm ERR!     at RegClient.<anonymous> (/tmp/staged/app/vendor/node/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:37:12)
       npm ERR!     at fs.readFile (fs.js:181:14)
       npm ERR!     at Object.oncomplete (fs.js:302:15)
       npm ERR! If you need help, you may report this log at:
       npm ERR!     <http://github.com/isaacs/npm/issues>
       npm ERR! or email it to:
       npm ERR!     <npm-@googlegroups.com>

       npm ERR! System Linux 3.13.0-39-generic
       npm ERR! command "/tmp/staged/app/vendor/node/bin/node" "/tmp/staged/app/vendor/node/bin/npm" "install" "--userconfig" "/tmp/staged/app/.npmrc" "--production"
       npm ERR! cwd /tmp/staged/app
       npm ERR! node -v v0.8.28
       npm ERR! npm -v 1.2.30

**Comment by YasuKatsuno** [comment]
It was fixed by updating package.json as folows.

{
"name": "bluemix-sample-tia-node",
"version": "0.1.0",
"engines": {
"node": "0.10.x"
},
"scripts": {
"start": "node lib/cli.js"
},
"dependencies": {
"async": "0.2.x",
"express": "3.3.x",
"nano": "5.10.0"
},
"devDependencies": {
"coffee-script": "1.6.x",
"shelljs": "0.1.x",
"supervisor": "0.5.x"
}
}
